向量链式法则

<img src="img/6.png" width="60%">

矩阵求导的两个例子
- EX1 <img src="img/7.png" width="64%">
- EX2 <img src="img/8.png" width="64%">

计算图

<img src="img/9.png" width="64%">

求梯度的反向传播算法

<img src="img/11.png" width="64%">

复杂度，神经网络为什么这么消耗GPU的原因，空间复杂度太大

<img src="img/8.png" width="64%">

In [4]:
x = torch.arange(4.0, requires_grad=True)
x.grad

In [5]:
y =  2 * torch.dot(x, x)
y # 

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

In [10]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [13]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [15]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad == d / a

tensor(True)