In [23]:
import torch

In [24]:
x = torch.arange(12)
x

tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,
         10.,  11.])

In [25]:
x.shape

torch.Size([12])

In [26]:
x.numel()

12

In [27]:
X = x.reshape(3, 4)
X

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])

In [28]:
torch.zeros((2, 3, 4))

tensor([[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]])

In [29]:
torch.ones(2, 3, 4)

tensor([[[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]],

        [[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]]])

In [30]:
torch.tensor([[2, 1, 4, 5], [1, 2, 3, 4]])

tensor([[ 2,  1,  4,  5],
        [ 1,  2,  3,  4]])

In [31]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2.0, 2, 2, 2])
x+y, x*y

(tensor([  3.,   4.,   6.,  10.]), tensor([  2.,   4.,   8.,  16.]))

In [32]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat([X, Y], dim=0), torch.cat([X, Y], dim=1)

(tensor([[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.],
         [  2.,   1.,   4.,   3.],
         [  1.,   2.,   3.,   4.],
         [  4.,   3.,   2.,   1.]]),
 tensor([[  0.,   1.,   2.,   3.,   2.,   1.,   4.,   3.],
         [  4.,   5.,   6.,   7.,   1.,   2.,   3.,   4.],
         [  8.,   9.,  10.,  11.,   4.,   3.,   2.,   1.]]))

In [33]:
# 通过逻辑运算符构建二维张量
X == Y

tensor([[ 0,  1,  0,  1],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]], dtype=torch.uint8)

In [34]:
X.sum()

tensor(66.)

In [35]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[ 0.],
         [ 1.],
         [ 2.]]),
 tensor([[ 0.,  1.]]))

In [36]:
# x，y形状不一样，我们可以调用广播机制来执行按元素操作，必须要求两个张量的维度相同
a.shape, b.shape, a + b # (3, 2)
# (a+b).shape = max(a.shape, b.shape) 

(torch.Size([3, 1]),
 torch.Size([1, 2]),
 tensor([[ 0.,  1.],
         [ 1.,  2.],
         [ 2.,  3.]]))

In [37]:
X[-1], X[1:3]

(tensor([  8.,   9.,  10.,  11.]),
 tensor([[  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]]))

In [38]:
# 指定索引来将元素写入矩阵
X[1, 2] = 9
X

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5.,   9.,   7.],
        [  8.,   9.,  10.,  11.]])

In [39]:
X[0:2, :]=12
X

tensor([[ 12.,  12.,  12.,  12.],
        [ 12.,  12.,  12.,  12.],
        [  8.,   9.,  10.,  11.]])

In [40]:
before = id(Y) # object Y 在python中唯一的标识号
Y = Y + X
id(Y) == before # 新的Y的id不等于之前Y的id

False

In [41]:
# 使用torch.zeros_like进行原地造作，对Z操作之后Z的id并没有改变
Z = torch.zeros_like(Y)
print('id(Z)', id(Z))
Z[:] = X + Y
print('id(Z)', id(Z))

id(Z) 2069209967496
id(Z) 2069209967496


In [42]:
before = id(X)
X += Y # += 也能进行原地操作
id(X) == before

True

In [45]:
a = torch.arange(12)
b = a.reshape((3,4))
b[:] = 2
a, b
# 使用reshape时把b改掉，a也改掉了，所以尽量不要修改

(tensor([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]),
 tensor([[ 2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.]]))

In [56]:
a = torch.tensor([2, 2, 2])
b = torch.tensor([3, 3, 3])
a = a.numpy()
b = b.numpy()
# * 一定是按元素逐个运算，四则运算都是，用*无法实现 a.T b @才是乘法
a * b, a.reshape((3, 1)).T @ b

(array([6, 6, 6], dtype=int64), array([18], dtype=int64))