In [51]:
import torch

In [52]:
A = torch.arange(20).reshape((5, 4))
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [53]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [54]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [55]:
B == B.T #B是一个转置换矩阵

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [56]:
X = torch.arange(24).reshape((2,3,4))
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [57]:
A = torch.arange(20, dtype=torch.float32).reshape(4, 5)
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.,  8.],
         [10., 12., 14., 16., 18.],
         [20., 22., 24., 26., 28.],
         [30., 32., 34., 36., 38.]]))

In [58]:
a = 2
X = torch.arange(24).reshape((2, 3, 4))
X + 2

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [59]:
A_sum_axis0 = X.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [60]:
A_sum_axis1 = X.sum(axis=1) # consider axis=1 means that it's a row in matrix, we will caculate the sum of each row
A_sum_axis1, A_sum_axis1.shape # specific axis will be throughout

(tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]))

In [61]:
A_sum_axis0 = X.sum(axis=[0, 1])
A_sum_axis0, A_sum_axis0.shape

(tensor([60, 66, 72, 78]), torch.Size([4]))

In [62]:
X / X.sum()

tensor([[[0.0000, 0.0036, 0.0072, 0.0109],
         [0.0145, 0.0181, 0.0217, 0.0254],
         [0.0290, 0.0326, 0.0362, 0.0399]],

        [[0.0435, 0.0471, 0.0507, 0.0543],
         [0.0580, 0.0616, 0.0652, 0.0688],
         [0.0725, 0.0761, 0.0797, 0.0833]]])

In [63]:
X.sum(axis=0).shape, X.sum(axis=0, keepdims=True).shape

(torch.Size([3, 4]), torch.Size([1, 3, 4]))

In [64]:
X , X.cumsum(axis=0) # ???????????????

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 14, 16, 18],
          [20, 22, 24, 26],
          [28, 30, 32, 34]]]))

In [65]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [66]:
X = torch.arange(20).reshape(5, 4)
y = torch.arange(4).reshape(4)
X.dtype, y.dtype, X.shape, y.shape, torch.mv(X, y).shape

(torch.int64,
 torch.int64,
 torch.Size([5, 4]),
 torch.Size([4]),
 torch.Size([5]))

In [67]:
# the matrix to multiple only need to be same  dtype , dtype is data type
A= torch.ones((5, 4), dtype=torch.float32)
B = torch.ones((4, 3), dtype=torch.float32)
torch.mm(A, B)
A

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum()

(tensor(5.), tensor(7.))

torch.norm(torch.ones(4, 9))
矩阵的范数

In [69]:
torch.norm(torch.ones(4, 9))
# 矩阵的范数

tensor(6.)

In [70]:
X = torch.ones(5, 4)
X.sum(axis=0, keepdims=True), X.sum(axis=1, keepdims=True)

(tensor([[5., 5., 5., 5.]]),
 tensor([[4.],
         [4.],
         [4.],
         [4.],
         [4.]]))