In [221]:
import torch

In [222]:
m = 100
# 生成一个包含有m个样本的数据集，每个样本有2个特征，1个标签
# 1. 生成特征数据，这应该是一个 m * 2 的matrix
X = torch.randn((m, 2)) # 每个值都是从 均值为 0 ，方差为 1 的标准正态分布中采样获得, 可以输出X.mean()和X.std()观察得到, randn应是 rand normal
print(X.mean(), X.std())

# 2. 生成标签数据，这应该是一个 m * 1 的vector, 我们一半值取1， 一半值取0
y = torch.cat([torch.zeros(int(m / 2),dtype=torch.int32), torch.ones(int(m / 2))], axis=0)
y
# 这里X 以及 1向量 和 0向量 cat 的 y 都是tensor， 因为我并没有指定它们的dtype(data type)为torch.float32 or torch.float64


tensor(0.0637) tensor(0.9876)


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [223]:
# 处理输入样本特征，为特征添加一个值为 1 的特征. 注意torch.ones参数要是 m, 1 否则它没有axis=1来和 X 进行concate
X = torch.cat([torch.ones(m,1), X], axis=1)
X

e-01, -1.1182e+00],
        [ 1.0000e+00,  1.4779e+00, -1.3806e+00],
        [ 1.0000e+00, -1.0055e+00,  2.3039e-01],
        [ 1.0000e+00, -3.1007e-01, -8.6014e-02],
        [ 1.0000e+00, -2.5664e-01,  8.7401e-01],
        [ 1.0000e+00, -1.7063e+00,  9.5552e-01],
        [ 1.0000e+00,  3.2069e-01,  1.3826e+00],
        [ 1.0000e+00, -1.2527e+00,  5.9950e-01],
        [ 1.0000e+00, -7.3443e-01, -4.0536e-01],
        [ 1.0000e+00,  6.3664e-01, -4.4485e-01],
        [ 1.0000e+00, -1.4488e+00,  1.7712e+00],
        [ 1.0000e+00,  2.4880e-01, -1.4894e+00],
        [ 1.0000e+00, -1.0759e+00,  1.4520e+00],
        [ 1.0000e+00,  7.5844e-01, -1.9787e-01],
        [ 1.0000e+00, -9.0210e-01,  7.5137e-01],
        [ 1.0000e+00,  9.7429e-01, -1.3163e-01],
        [ 1.0000e+00, -1.1640e+00,  7.7195e-01],
        [ 1.0000e+00,  6.3517e-01,  4.8320e-01],
        [ 1.0000e+00,  6.1315e-01,  1.1784e+00],
        [ 1.0000e+00, -4.1494e-01,  2.4502e-01],
        [ 1.0000e+00,  7.4884e-01,  2.7826e-01]])

In [224]:
# 初始化模型参数theta, [theta_0, theta_1, theta_2]
theta = torch.zeros(3, requires_grad=True)# 我们后面构造的计算图需要对它求梯度用来更新参数
theta

tensor([0., 0., 0.], requires_grad=True)

In [225]:
def sigmoid(z):
    return 1 / (1 + torch.exp(z))
def h(theta, X):
    return sigmoid(torch.mv(X, theta))

In [226]:
# 构造计算loss的计算图，对于loss，我们只要写出它与输入X之间关系的表达式就行
def get_loss(theta, X, y):
    loss = - torch.dot(y, torch.log(h(theta, X))) + torch.dot((1-y), torch.log(h(theta, X))).sum()
    return loss 
# 设定学习率
alpha = 0.01
epochs = 100

In [227]:
loss = get_loss(theta, X, y)
loss.backward(retain_graph=True)
print(theta.grad)
# theta.grad.zero_()
theta.grad

tensor([  0.0000, -12.1060,   5.4159])


tensor([  0.0000, -12.1060,   5.4159])

In [228]:
# 记录损失值得变化
losses = []
for _ in range(epochs):
    # theta梯度置为0
    theta.grad.zero_()
    loss.backward()
    grad = theta.grad
    # print(grad)
    # 参数theta更新, 在pytorch中这样更新参数改变叶子变量的值是不可以的，pytoch有对应的函数来对其进行参数更新
    theta -= alpha * grad
    # 计算损失并记录
    loss = get_loss(theta, X, y)
    losses.append(loss)
theta, losses

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.